language: python

python:
  - "3.9"
  - "3.8"

env:
  - DJANGO="https://github.com/django/django/archive/main.tar.gz"
  - DJANGO="Django>=3.1,<3.2"

install:
  - pip install -q $DJANGO
  - pip install coveralls

script:
  - python -Wall tests/manage.py test tests --settings=settings
  - coverage run --omit='quicktest.py,setup.py' --source=. tests/manage.py test tests

after_success: coveralls

matrix:
  allow_failures:
    - env: DJANGO="https://github.com/django/django/archive/main.tar.gz"

  include:
    - python: "3.6"
      env: DJANGO="Django>=3.2,<4.0"
    - python: "3.7"
      env: DJANGO="Django>=3.2,<4.0"
    - python: "3.8"
      env: DJANGO="Django>=3.2,<4.0"
    - python: "3.9"
      env: DJANGO="Django>=3.2,<4.0"

    - python: "3.6"
      env: DJANGO="Django>=3.1,<3.2"
    - python: "3.7"
      env: DJANGO="Django>=3.1,<3.2"
    - python: "3.8"
      env: DJANGO="Django>=3.1,<3.2"
    - python: "3.9"
      env: DJANGO="Django>=3.1,<3.2"

    - python: "3.6"
      env: DJANGO="Django>=3.0,<3.1"
    - python: "3.7"
      env: DJANGO="Django>=3.0,<3.1"
    - python: "3.8"
      env: DJANGO="Django>=3.0,<3.1"
    - python: "3.9"
      env: DJANGO="Django>=3.0,<3.1"

    - python: "3.5"
      env: DJANGO="Django>=2.2,<3.0"
    - python: "3.6"
      env: DJANGO="Django>=2.2,<3.0"
    - python: "3.7"
      env: DJANGO="Django>=2.2,<3.0"
    - python: "3.8"
      env: DJANGO="Django>=2.2,<3.0"
    - python: "3.9"
      env: DJANGO="Django>=2.2,<3.0"

    - python: "3.5"
      env: DJANGO="Django>=2.1,<2.2"
    - python: "3.6"
      env: DJANGO="Django>=2.1,<2.2"
    - python: "3.7"
      env: DJANGO="Django>=2.1,<2.2"

    - python: "3.4"
      env: DJANGO="Django>=2.0,<2.1"
    - python: "3.5"
      env: DJANGO="Django>=2.0,<2.1"
    - python: "3.6"
      env: DJANGO="Django>=2.0,<2.1"
    - python: "3.7"
      env: DJANGO="Django>=2.0,<2.1"

    - python: "2.7"
      env: DJANGO="Django>=1.11,<2.0"
    - python: "3.4"
      env: DJANGO="Django>=1.11,<2.0"
    - python: "3.5"
      env: DJANGO="Django>=1.11,<2.0"
    - python: "3.6"
      env: DJANGO="Django>=1.11,<2.0"
    - python: "3.7"
      env: DJANGO="Django>=1.11,<2.0"

    - python: "2.7"
      env: DJANGO="Django>=1.10,<1.11"
    - python: "3.4"
      env: DJANGO="Django>=1.10,<1.11"
    - python: "3.5"
      env: DJANGO="Django>=1.10,<1.11"

    - python: "2.7"
      env: DJANGO="Django>=1.9,<1.10"
    - python: "3.4"
      env: DJANGO="Django>=1.9,<1.10"
    - python: "3.5"
      env: DJANGO="Django>=1.9,<1.10"

    - python: "2.7"
      env: DJANGO="Django>=1.8,<1.9"
    - python: "3.4"
      env: DJANGO="Django>=1.8,<1.9"
    - python: "3.5"
      env: DJANGO="Django>=1.8,<1.9"
